# Generated by Django 5.2 on 2025-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/user-photo/user01.png', upload_to='user-photo/'),
        ),
    ]
