# Generated by Django 5.2 on 2025-04-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(default='user-photo/user-default.jpg', upload_to='user-photo/'),
        ),
    ]
